version: '3.8'

services:
  app:
    image: app:0.3
    depends_on:
      - rental
    ports:
      - "8080:8080"
    networks:
      vaganda:
  rental:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      vaganda:
  nexus:
    image: sonatype/nexus3:3.78.2-java17-alpine
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/some-other-dir
    networks:
      vaganda:
  jenkins:
    image: custom-jenkins:0.2.4
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root
    ports:
      - "8082:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - ssh_volume:/var/jenkins_home/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      vaganda:
volumes:
  data:
  nexus-data:
  jenkins_data:
  ssh_volume:
networks:
  vaganda:



  #меняй версию образа докера перед запуском
  #vaganda название сети связи докера между приложениями(контейнерами)




