version: "3.8"

services:
  rental-service:
    image: rental-service:1.0.0
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    container_name: postgres-service
    ports:
      - "7772:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge