version: "3.8"

services:
  rental:
    image: rental:1.0.0
    ports:
      - "7874:7874"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      RENTAL_DATASOURCE_URL: jdbc:postgresql://postgres-rental:5432/postgres
      RENTAL_DATASOURSE_USERNAME: admin
      RENTAL_DATASOURSE_PASSWORD: admin
      USER_URL: http://user:7873/api/users

  postgres:
    image: postgres:17.4
    container_name: postgres_rental
    ports:
      - "7773:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge